/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface DemoChild {
    'first': string;
    'last': string;
    'middle': string;
  }
  interface DemoChildAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'DemoChild': Components.DemoChild;
  }

  interface StencilIntrinsicElements {
    'demo-child': Components.DemoChildAttributes;
  }


  interface HTMLDemoChildElement extends Components.DemoChild, HTMLStencilElement {}
  var HTMLDemoChildElement: {
    prototype: HTMLDemoChildElement;
    new (): HTMLDemoChildElement;
  };

  interface HTMLElementTagNameMap {
    'demo-child': HTMLDemoChildElement
  }

  interface ElementTagNameMap {
    'demo-child': HTMLDemoChildElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
