/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import 'demo-child';


export namespace Components {

  interface DemoParentTwo {
    'first': string;
    'last': string;
    'middle': string;
  }
  interface DemoParentTwoAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'DemoParentTwo': Components.DemoParentTwo;
  }

  interface StencilIntrinsicElements {
    'demo-parent-two': Components.DemoParentTwoAttributes;
  }


  interface HTMLDemoParentTwoElement extends Components.DemoParentTwo, HTMLStencilElement {}
  var HTMLDemoParentTwoElement: {
    prototype: HTMLDemoParentTwoElement;
    new (): HTMLDemoParentTwoElement;
  };

  interface HTMLElementTagNameMap {
    'demo-parent-two': HTMLDemoParentTwoElement
  }

  interface ElementTagNameMap {
    'demo-parent-two': HTMLDemoParentTwoElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
